# Generated by Django 3.0.4 on 2020-04-02 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officecode', models.AutoField(primary_key=True, serialize=False)),
                ('officename', models.CharField(max_length=20)),
                ('attribution', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organizationCode', models.AutoField(primary_key=True, serialize=False)),
                ('organizationname', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=20)),
                ('datejoined', models.DateField()),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('citystate', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('servicecode', models.AutoField(primary_key=True, serialize=False)),
                ('servicesname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('premium', models.CharField(max_length=20)),
                ('allocation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('subscriptiontypecode', models.AutoField(primary_key=True, serialize=False)),
                ('subscriptiontypename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=20)),
                ('mName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('cellPhone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('transferID', models.AutoField(primary_key=True, serialize=False)),
                ('transferFrom', models.CharField(max_length=20)),
                ('transferTo', models.CharField(max_length=20)),
                ('requestDate', models.DateField()),
                ('transferDate', models.DateField()),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriberID', models.AutoField(primary_key=True, serialize=False)),
                ('servicecode', models.CharField(max_length=20)),
                ('requestdate', models.DateField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('motifofcancellation', models.CharField(max_length=20)),
                ('subscriptiontypecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubscriptionType')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('nativecountry', models.CharField(max_length=20)),
                ('citizenship', models.CharField(max_length=20)),
                ('isdelegate', models.BooleanField(default=False)),
                ('organizationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Organization')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('officecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Office')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
    ]
