# Generated by Django 3.0.4 on 2020-04-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200401_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='citystate',
            new_name='city',
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
