# Generated by Django 3.0.4 on 2020-04-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
