# Generated by Django 3.0.4 on 2020-04-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200322_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='portal',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
